### ISSUE TITLE
Duplicate content issue

### ISSUE THREAD

**Issue by JelleGe** [customgento/module-default-store-code-remover-m2#8] opened 2023-06-22 19:19 UTC
There is a duplicate content issue when installing this module, because the default store is available with and with the default store code inside the URL.

This should be a 301 redirect to avoid duplicate content for SEO

**Comment by sprankhub** [comment] 2023-06-23 08:30
Duplicate of #5.

**Closed as completed by sprankhub** 2023-06-23 08:30 UTC
